### ISSUE TITLE
Suggestion: Weapon Categories

### ISSUE THREAD

**Issue by yay855** [DummieNaime/The-Funni-Mod#1]
Cataclysm BN has weapon categories as part of its systems now, which allow you to make modded martial arts and modded weapons interact more nicely. Maces, fist weapons, and bionic weaponry are all weapon categories one can assign to weapons, and it may suit you to make your weapons fit into those categories for the purposes of martial arts instead of manually adding them to the (base game) martial arts styles.

**Comment by yay855** [comment]
Wait, I'm blind, it's right there, you just ALSO added the weapons to specific martial arts that the weapon flags would already have covered. You can just dummy out the martial arts file for now, in that case.

**Comment by DummieNaime** [comment]
Alright, thanks!
